FROM php:8.3-cli

# Cài Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

# Cài dependencies PHP
RUN composer install
# đảm bảo cron.sh có quyền chạy
RUN chmod +x cron.sh

CMD ["sh", "cron.sh"]